# Generated by Django 2.0.1 on 2018-04-23 14:56

import constrainedfilefield.fields
import control.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cover', constrainedfilefield.fields.ConstrainedFileField(blank=True, content_types=['image/jpeg', 'image/png'], max_upload_size=512000, mime_lookup_length=4096, null=True, upload_to=control.models.board_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sound', constrainedfilefield.fields.ConstrainedFileField(content_types=['audio/mpeg', 'audio/mp3'], max_upload_size=250000, mime_lookup_length=4096, upload_to=control.models.clip_upload_handler)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Board')),
            ],
        ),
        migrations.AddField(
            model_name='alias',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Clip'),
        ),
        migrations.AlterUniqueTogether(
            name='clip',
            unique_together={('name', 'board')},
        ),
    ]
