# Generated by Django 2.0.6 on 2018-06-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alias',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='alias',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
