# Generated by Django 2.0.1 on 2018-09-25 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_appuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='refresh_token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
