# Generated by Django 2.0.1 on 2018-09-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20180925_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Clip')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Playlist')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playlistclip',
            unique_together={('clip', 'playlist')},
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('name', 'user')},
        ),
    ]
